name: CI

# Triggered when code is pushed to any branch in a repository
on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node: 12.x
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run -s lint
